Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,9 +26,17 @@ jobs:
     - name: Install Dependencies and Build App
       run: |
         ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
-          cd /root/menu
+          cd /root/frontend  # Use the correct path used in rsync
           npm install
-          cp .env.production .env
+          if [ -f .env.production ]; then
+            cp .env.production .env
+          fi
           NODE_ENV=production npm run build
-          sudo cp -rf build/* /usr/share/nginx/html/menu
+          if [ -d build ]; then
+            sudo cp -rf build/* /usr/share/nginx/html/menu
+          else
+            echo "Build directory not found!"
+            exit 1
+          fi
         EOF
+
